name: 'Run sample tests'
description: 'Run sample tests on emulator'
inputs:
  api-level:
    required: true
    description: 'API level'
    default: '30'

runs:
  using: composite
  steps:
    - name: Run sample tests. Api ${{ inputs.api-level }}
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ inputs.api-level }}
        arch: x86_64
        script: |
          adb devices
          ./gradlew :samples:testDebug --tests "fi.epicbot.toster.samples.SampleFontSizeTest" --stacktrace
          ./gradlew :samples:testDebug --tests "fi.epicbot.toster.samples.SampleLanguageTest" --stacktrace
          ./gradlew :samples:testDebug --tests "fi.epicbot.toster.samples.SampleOverdrawTest" --stacktrace
          ./gradlew :samples:testDebug --tests "fi.epicbot.toster.samples.SampleParamsTest" --stacktrace

    - name: publish screenshot
      uses: actions/upload-artifact@v2
      with:
        name: SampleTestOutput_api${{ inputs.api-level }}
        path: samples/build/toster/

    - name: publish log files
      uses: actions/upload-artifact@v2
      with:
        name: SampleTestLog_api${{ inputs.api-level }}
        path: samples/build/toster/*/log.txt