name: Build DSL

on: pull_request

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-environment
        name: Prepare environment

      - name: Run Static Analysis
        run: ./gradlew detekt

  unit-tests:
    needs: [static-analysis]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-environment
        name: Prepare environment

      - name: Run Unit Tests
        run: ./gradlew :lib:testDebugUnitTest

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: lib/build/test-results/**/*.xml

      - name: Run Coverage task
        run: ./gradlew koverReport

      - name: Public Coverage reports
        uses: codecov/codecov-action@v2
        with:
          files: build/reports/kover/report.xml

  build-dsl:
    needs: [unit-tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-environment
        name: Prepare environment

      - name: Build DSL
        run: ./gradlew :lib:assembleRelease

      - name: Build samples
        run: ./gradlew :samples:assembleDebug

      - uses: ./.github/actions/cache-builds
        name: Save cache builds

  test-samples:
    needs: [build-dsl]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [ 21, 23, 26, 30 ]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-environment
        name: Prepare environment

      - uses: ./.github/actions/cache-builds
        name: Restore cache builds

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          script: |
            adb devices & ./gradlew :samples:testDebug --tests "fi.epicbot.toster.samples.SampleParamsTest" --stacktrace

      - name: publish screenshot
        uses: actions/upload-artifact@v2
        with:
          name: SampleTestOutput_api${{ matrix.api-level }}
          path: samples/build/toster/Samples/UUID

      - name: publish log files
        uses: actions/upload-artifact@v2
        with:
          name: SampleTestLog_api${{ matrix.api-level }}
          path: samples/build/toster/Samples/log.txt
