name: Build DSL

on: pull_request

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-environment
        name: Prepare environment

      - name: Run Static Analysis
        run: ./gradlew detekt

  unit-tests:
    needs: [static-analysis]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-environment
        name: Prepare environment

      - name: Run Unit Tests
        run: ./gradlew :lib:testDebugUnitTest

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: lib/build/test-results/**/*.xml

  build-dsl:
    needs: [unit-tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-environment
        name: Prepare environment

      - name: Build DSL
        run: ./gradlew :lib:assembleRelease

  test-samples:
    needs: [static-analysis]
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-environment
        name: Prepare environment

      - uses: ./.github/actions/run-sample-tests
        name: Run 23
        with:
          api-level: '23'

      - uses: ./.github/actions/run-sample-tests
        name: Run 26
        with:
          api-level: '26'

      - uses: ./.github/actions/run-sample-tests
        name: Run 30
        with:
          api-level: '30'
