name: Build DSL

on: pull_request

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-environment
        name: Prepare environment

      - name: Run Static Analysis
        run: ./gradlew detekt

  unit-tests:
    needs: [static-analysis]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-environment
        name: Prepare environment

      - name: Run Unit Tests
        run: ./gradlew :lib:testDebugUnitTest

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: lib/build/test-results/**/*.xml

      - name: Run Coverage task
        run: ./gradlew koverReport

      - name: Public Coverage reports
        uses: codecov/codecov-action@v2
        with:
          files: build/reports/kover/report.xml

  build-dsl:
    needs: [unit-tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-environment
        name: Prepare environment

      - name: Build DSL
        run: ./gradlew :lib:assembleRelease

  mutation-tests:
    needs: [ unit-tests ]
    if: ${{ false }} # TODO [77]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-environment
        name: Prepare environment

      - name: Run mutation tests
        run: ./gradlew :lib:pitestDebug

  build-samples:
    needs: [build-dsl]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-environment
        name: Prepare environment

      - name: Build Samples
        run: ./gradlew :samples:assembleRelease