name: Library availability

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  check-libs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lib-versions: [ "0.2.9", "0.2.8", "0.2.7", "0.2.6", "0.2.5" ]
        gradle-plugins: [ "7.4" ]
        gradle-tools: [ "7.1.1" ]
        kotlin-version: [ "1.6.20" ]
        include:

          - gradle-plugins: "7.0.2"
            gradle-tools: "7.0.2"
            kotlin-version: "1.5.31"
            lib-versions: "0.2.9"

          - gradle-plugins: "6.2.2"
            gradle-tools: "3.5.3"
            kotlin-version: "1.3.71"
            lib-versions: "0.2.9"

          - gradle-plugins: "6.1.1"
            gradle-tools: "4.0.0"
            kotlin-version: "1.3.72"
            lib-versions: "0.2.9"

      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: Change wrapper permissions
        shell: bash
        run: chmod +x ./gradlew

      - name: Prepare tmp project
        run: python3 scripts/check_lib_availability.py -v=${{ matrix.lib-versions }} -p=${{ matrix.gradle-plugins }} -t=${{ matrix.gradle-tools }} -k=${{ matrix.kotlin-version }}

      - name: Download deps
        run: sh scripts/check_deps.sh

      - name: Send message on fail
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Job: Library availability
            lib-versions: ${{ matrix.lib-versions }}
            gradle-plugins: ${{ matrix.gradle-plugins }}
            gradle-tools: ${{ matrix.gradle-tools }}
            kotlin-version: ${{ matrix.kotlin-version }}
            Repository: ${{ github.repository }}
            Status: Failure
