name: Mutation tests

on:
  schedule:
    - cron: '0 2 * * *'

jobs:

  mutation-tests:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-environment
        name: Prepare environment

      - name: Run mutation tests
        run: ./gradlew :lib:pitestDebug

      - name: publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MutationTestOutput
          path: lib/build/reports/pitest/
